### PR TITLE
first attempt

### PR DESCRIPTION
**Pull request by VinceG**
Regarding #164

### CODE REVIEW

**Comment by VinceG** [comment]
@evert Let me know what you want me to change. thank you.

**Comment by evert** [comment]
If the robots say it's good, we'll merge =)

**Comment by VinceG** [comment]
Looks like some failed but it's unrelated to to this change though.

**Comment by evert** [comment]
Agreed

**Comment by VinceG** [comment]
@evert Thank You! Looking forward for that tag. Thanks again.

**Comment by DeepDiver1975** [comment]
Next time please squach your commits. We should try to preserve a clean commit history. THX

**Comment by VinceG** [comment]
@DeepDiver1975 Will do, sorry about that.

**Comment by evert** [comment]
I could have also done that with a press of a button. Sorry!

**Comment by VinceG** [comment]
@evert @DeepDiver1975 hey guys, can we have a new tag for this project? It’s been couple of months and we are still using dev-master .

**Pull request merged**
