### PR TITLE
Check CI for 2.2

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by phil-davis** [comment]
PHP CS Fixer 3.64.0 wants to add a trailing comma to the parameters of the `list()` "function"

But the old PHP CS fixer v2 does not require that, and in fact it tries to refactor the code removing the trailing comma.
It is getting more difficult to keep supporting all the way from PHP 7.1 to 8.4 and with the different major versions of the code style and analysis tools.

**Comment by staabm** [comment]
IMO dropping 7.x (or everything below 7.4h should be considered

**Comment by phil-davis** [comment]
> IMO dropping 7.x (or everything below 7.4h should be considered

Agree - I will set all the repos to a minimum of 7.4 supported. The analysis tools are all still supporting that OK, and 7.4 has a good range of the "new" code styling options available.

**Comment by phil-davis** [comment]
I got it passing in #298 by pinning php-cs-fixer to 3.63.2 - that will do for now.

**Pull request closed without merging**
