### PR TITLE
Use phpunit8

### PR DESCRIPTION
**Pull request by phil-davis**
See last commit.

This is on top of #173

### CODE REVIEW

**Comment by staabm** [comment]
> This is on top of #173

hmm .. I guess I merged it in the wrong order.. could you rebase the PR?

how was I supposed to handle this situation instead?

**Comment by phil-davis** [comment]
> how was I supposed to handle this situation instead?

I have no idea why it said that there was a conflict. I rebased and did not have to manually resolve any conflict, and the diffs look fine.

**Comment by phil-davis** [comment]
@staabm IMO all the "sub"-repos now have PHP 7.4 support and run phpunit8.

So whenever you like, releases can be made. And then someone can update `sabre-io/dav` with all the dependencies and make it support PHP 7.4 and phpunit8.

Then that will let downstream users of these packages use the new versions and officially support PHP 7.4

**Comment by staabm** [comment]
Thank you so much - great job. Well done

**Pull request merged**
